#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using BankingSite;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/LoanApplication/Apply.cshtml")]
    public partial class _Views_LoanApplication_Apply_cshtml : System.Web.Mvc.WebViewPage<BankingSite.Models.LoanApplication>
    {
        public _Views_LoanApplication_Apply_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\LoanApplication\Apply.cshtml"
  
    ViewBag.Title = "Loan Application";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 7 "..\..\Views\LoanApplication\Apply.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n");

            
            #line 9 "..\..\Views\LoanApplication\Apply.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\LoanApplication\Apply.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\LoanApplication\Apply.cshtml"
                                 


            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <legend>Application Details</legend>\r\n\r\n        <div>\r\n");

WriteLiteral("            ");

            
            #line 17 "..\..\Views\LoanApplication\Apply.cshtml"
       Write(Html.LabelFor(model => model.FirstName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 18 "..\..\Views\LoanApplication\Apply.cshtml"
       Write(Html.EditorFor(model => model.FirstName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 19 "..\..\Views\LoanApplication\Apply.cshtml"
       Write(Html.ValidationMessageFor(model => model.FirstName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div>\r\n");

WriteLiteral("            ");

            
            #line 23 "..\..\Views\LoanApplication\Apply.cshtml"
       Write(Html.LabelFor(model => model.LastName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 24 "..\..\Views\LoanApplication\Apply.cshtml"
       Write(Html.EditorFor(model => model.LastName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 25 "..\..\Views\LoanApplication\Apply.cshtml"
       Write(Html.ValidationMessageFor(model => model.LastName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>        \r\n        \r\n        <div>\r\n");

WriteLiteral("            ");

            
            #line 29 "..\..\Views\LoanApplication\Apply.cshtml"
       Write(Html.LabelFor(model => model.Age));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 30 "..\..\Views\LoanApplication\Apply.cshtml"
       Write(Html.EditorFor(model => model.Age));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 31 "..\..\Views\LoanApplication\Apply.cshtml"
       Write(Html.ValidationMessageFor(model => model.Age));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        \r\n        <div>\r\n");

WriteLiteral("            ");

            
            #line 35 "..\..\Views\LoanApplication\Apply.cshtml"
       Write(Html.LabelFor(model => model.AnnualIncome));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 36 "..\..\Views\LoanApplication\Apply.cshtml"
       Write(Html.EditorFor(model => model.AnnualIncome));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 37 "..\..\Views\LoanApplication\Apply.cshtml"
       Write(Html.ValidationMessageFor(model => model.AnnualIncome));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>        \r\n\r\n        <p>\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Apply\"");

WriteLiteral(" id=\"Apply\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" />\r\n        </p>\r\n    </fieldset>\r\n");

            
            #line 44 "..\..\Views\LoanApplication\Apply.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
